language: erlang

otp_release:
  - 21.1
  - 20.3
  - 19.3

sudo: false

addons:
  apt:
    packages:
      - libmozjs185-dev

before_install:
  - git clone --depth 1 https://github.com/apache/couchdb -b 3.1.1

before_script:
  - cd couchdb
  - ./configure --disable-docs --disable-fauxton
  - cp -r ../!(couchdb) ./src/config
  - make

script:
  - make eunit apps=config

cache: apt
